volumes:
  lidas-database:

services:
  gatewayapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.GatewayApi/Dockerfile
    ports:
       - "5000:8080"
    networks:
       - lidas-network

  userapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.UserApi/Dockerfile
    depends_on:
       - postgres
       - rabbitmq
    networks:
       - lidas-network

  mangaapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.MangaApi/Dockerfile
    depends_on:
       - postgres
       - rabbitmq
    networks:
       - lidas-network

  wishlistapi:
     build:
       context: ../Lidas
       dockerfile: Lidas.WishlistApi/Dockerfile
     depends_on:
       - postgres
       - rabbitmq
     networks:
       - lidas-network

  likeapi:
     build:
       context: ../Lidas
       dockerfile: Lidas.LikeApi/Dockerfile
     depends_on:
       - postgres
       - rabbitmq
     networks:
       - lidas-network
       
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - lidas-database:/var/lib/postgresql
    networks:
      - lidas-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - lidas-network

networks:
  lidas-network:
    driver: bridge