services:
  gatewayapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.GatewayApi/Dockerfile
    ports:
       - "5000:8080"

  userapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.UserApi/Dockerfile
    depends_on:
        - rabbitmq

  mangaapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.MangaApi/Dockerfile
    depends_on:
        - rabbitmq

  wishlistapi:
     build:
       context: ../Lidas
       dockerfile: Lidas.WishlistApi/Dockerfile
     ports:
        - "8080:8080"
     depends_on:
        - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"