services:
  gatewayapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.GatewayApi/Dockerfile
    ports:
       - "5000:8080"
    networks:
       - lidas-network

  userapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.UserApi/Dockerfile
    depends_on:
       - rabbitmq
    networks:
       - lidas-network

  mangaapi:
    build:
      context: ../Lidas
      dockerfile: Lidas.MangaApi/Dockerfile
    depends_on:
       - rabbitmq
    networks:
       - lidas-network

  wishlistapi:
     build:
       context: ../Lidas
       dockerfile: Lidas.WishlistApi/Dockerfile
     depends_on:
       - rabbitmq
     networks:
       - lidas-network

  likeapi:
     build:
       context: ../Lidas
       dockerfile: Lidas.LikeApi/Dockerfile
     ports:
       - "8080:8080"
     depends_on:
       - rabbitmq
     networks:
       - lidas-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - lidas-network

networks:
  lidas-network:
    driver: bridge